const ROLES = {
  ADMIN: 'Admin',
  VIGILANT: 'Vigilant',
  RESIDENT: 'Resident',
  SUPER_ADMIN: 'SuperAdmin'
}

const SMART_RESIDENTIAL = {
  TOKEN: 'SMART_RESIDENTIAL_TOKEN',
  LANGUAGE: 'SMART_RESIDENTIAL_LANGUAGE',
  IS_DARK_THEME: 'SMART_RESIDENTIAL_IS_DARK_THEME'
}

const SNACKBAR_COLOR = {
  INFO: 'info',
  ERROR: 'error',
  SUCCESS: 'success'
}

export {
  ROLES,
  SNACKBAR_COLOR,
  SMART_RESIDENTIAL
}
